import tkinter as tk
mama = tk.Tk()
mama.geometry("500x300")
mama.title("Моя твоя не понимать")
label = tk.Label(mama, text="Hello mir, manera krytit mir", font=("Arial", 20))
label.pack(padx=15, pady=15)
textbox = tk.Text(mama, height=3, font=("Arial", 13))
buttonFrame = tk.Frame(mama)
buttonFrame.columnconfigure(0, weight=2)
buttonFrame.columnconfigure(1, weight=2)
buttonFrame.columnconfigure(2, weight=2)
buttonFrame.columnconfigure(3, weight=2)
btn1 = tk.Button(buttonFrame, text="1", font=("Arial", 15))
btn2 = tk.Button(buttonFrame, text="2", font=("Arial", 15))
btn3 = tk.Button(buttonFrame, text="3", font=("Arial", 15))
btn4 = tk.Button(buttonFrame, text="4", font=("Arial", 15))
btn5 = tk.Button(buttonFrame, text="5", font=("Arial", 15))
btn6 = tk.Button(buttonFrame, text="6", font=("Arial", 15))
btn7 = tk.Button(buttonFrame, text="7", font=("Arial", 15))
btn8 = tk.Button(buttonFrame, text="8", font=("Arial", 15))
btn9 = tk.Button(buttonFrame, text="9", font=("Arial", 15))
btn0 = tk.Button(buttonFrame, text="0", font=("Arial", 15))
btn1.grid(row=0, column=0, sticky="we")
btn2.grid(row=0, column=1, sticky="we")
btn3.grid(row=0, column=2, sticky="we")
btn4.grid(row=1, column=0, sticky="we")
btn5.grid(row=1, column=1, sticky="we")
btn6.grid(row=2, column=1, sticky="we")
btn7.grid(row=0, column=2, sticky="we")
btn8.grid(row=1, column=2, sticky="we")
btn9.grid(row=2, column=2, sticky="we")
btn0.grid(row=1, column=3, sticky="we")
buttonFrame.pack(fill="x")
# root.mainloop()